[pytest]
testpaths = 
    tests

pythonpath = .

addopts = -v --html=pytest_report.html --self-contained-html

markers =
    map: тести, пов'язані з мапою
    map_generation: тести генерації мапи
    pathfinding: тести пошуку шляху в тунелях
    pellets: тести логіки пелетів