[pytest]
testpaths = 
    tests

pythonpath = .

addopts = -v --html=pytest_report.html --self-contained-html

markers =
    map: тести, пов'язані з мапою
    map_generation: тести генерації мапи
    pathfinding: тести пошуку шляху в тунелях
    pellets: тести логіки пелетів
    ghost_logic: логіка окремих привидів та їхніх стратегій
    ghost_manager: перемикання режимів та таймери менеджера
    math_logic: tests for mathematical calculations and coordinates
    game_logic: tests for core game mechanics and states
    powerups: tests for pacman powerups
    pac_spawn: PACMAN tests spawn
    pac_movement: PACMAN tests movement
    pac_eating: PACMAN tests eating and powerup logic
    pac_tunnels: PACMAN tests tunnel teleportation
    pac_ghosts: PACMAN tests interaction with ghosts
    pac_timers: PACMAN tests powerup and invicibility timers
    pac_state: PACMAN tests influence on game state
