[pytest]
testpaths = 
    tests

pythonpath = .

addopts = -v --ignore=tests/pacman_test.py --html=pytest_report.html --self-contained-html

markers =
    map: тести, пов'язані з мапою
    game_map: юніт-тести для класу GameMap
    map_generation: тести генерації мапи
    pathfinding: тести пошуку шляху в тунелях
    pellets: тести логіки пелетів
    difficulty_manager: юніт-тести для менеджера складності
    seeded_random: юніт-тести для генератора випадкових чисел із seed