class GraphicsConfig:
    DOT_SIZE_DIVISOR = 10
    MIN_DOT_SIZE = 2
    POWER_PELLET_SIZE_DIVISOR = 4
    MIN_POWER_PELLET_SIZE = 5
    WALL_BORDER_WIDTH = 2
    TEXT_FONT_SIZE = 36
    TEXT_PADDING = 20
    TEXT_MARGIN = 10

class CameraConfig:
    ACCELERATION = 0.5
    FRICTION = 0.85
    MIN_VELOCITY = 0.1
    SPEED_DIVISOR = 3

class GameConfig:
    PACMAN_SPEED_MS = 200
    CAMERA_SMOOTHING = 0.15
    CAMERA_MARGIN_PCT = 0.3
    MOUTH_ANIM_SPEED = 100
    PACMAN_RADIUS_OFFSET = 2